# Results

With all of our work constructing the regression complete, we are now ready to interpret the results of Table 1. The baseline model assumes that no factors affect sentencing except race, so race is our independent variable and total sentence length is the dependent variable. Because the independent variable race is categorical, we code one of the values of that variable (one race) with a value of zero and call that value the reference level. In this case, the race white was coded as the reference value and the races Black, Hispanic, and ARI are compared against it.

We see that, accounting for nothing other than race, Black defendants received on average sentences that were 18.5 months longer than white defendants. Similarly, Hispanic defendants receive sentences that are 5.3 months longer than those of white defendants. Note that the confidence intervals for these estimates are also provided (see the previous case study for discussion of confidence intervals). Defendants classified as ARI receive sentences that are 9.0 months shorter than white defendants on average. Why might that be? We need to be careful in drawing conclusions from this initial model because we have not yet tried to explain those differences based on other factors, such as year or criminal history.

As we add and consider factors that might explain some of this variation, we expect to see this differential in sentencing length change. In no particular order, the other explanatory variables are added to the model. For example, when demographic information is included, the differential in sentencing length for Black defendants drops by $(18.5-12.9) = 5.6$ months. With demographic factors added as independent variables, Black defendants receive on average sentences that are 12.9 years longer than white defendants. The researchers included other explanatory variables, including factors considered in the sentencing guidelines. In the end, with all explanatory variables included, we find that Black defendants receive sentences on average 1.9 months longer than white defendants and Hispanic defendants receive sentences at the same length as white defendants.

It is worth noting in the comments at the bottom of the table that the adjusted $r^2$ values are reported. This allows us to determine how much of the variation in sentencing is explained by the independent variables considered in the model. For the baseline model, the adjusted $r^2$ is 0.02, meaning that only 2% of the variability in sentence length is explained by the baseline model. For the full model, the adjusted $r^2$ is reported as 0.79, meaning that 79% of the variability in sentence length is explained by the full model. The adjusted $r^2$ is reported instead of $r^2$ because adjusted $r^2$ adjusts for the number of independent variables included in the model. As we add explanatory variables, $r^2$ will likely increase, but it might be a spurious increase. The adjusted $r^2$ takes the number of variables into account so is reported in multivariate regressions.

The authors further refine the analysis by looking at individual districts rather than the federal court system nationwide. We focus our examination on the results of Model II, which are reported in Table 3. We see that Black defendants receive longer sentences than white defendants in 11 districts and ARI defendants receive longer sentences than white defendants in 3 districts. Figure 3 pulls out these districts and provides the 95% confidence interval for the sentence differential and Figure 4 highlights the locations of these districts in the U.S.